// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj7y8wHNIt1TG8q6UkD5WHXBlXvgUAb_g',
    appId: '1:987615597119:web:fa5ef70c66e664330e5e8a',
    messagingSenderId: '987615597119',
    projectId: 'personalnote-37151',
    authDomain: 'personalnote-37151.firebaseapp.com',
    storageBucket: 'personalnote-37151.firebasestorage.app',
    measurementId: 'G-574Y940VY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-_UcOd4K8nkKHsAKXW_gLPmm-Iv1LNco',
    appId: '1:987615597119:android:e2b9e2259b94e4730e5e8a',
    messagingSenderId: '987615597119',
    projectId: 'personalnote-37151',
    storageBucket: 'personalnote-37151.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3oqaaX_uUqP0Njl3KK48-kcPB9YPq2TI',
    appId: '1:987615597119:ios:4ed89e2f209a7e950e5e8a',
    messagingSenderId: '987615597119',
    projectId: 'personalnote-37151',
    storageBucket: 'personalnote-37151.firebasestorage.app',
    iosBundleId: 'com.example.securityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3oqaaX_uUqP0Njl3KK48-kcPB9YPq2TI',
    appId: '1:987615597119:ios:4ed89e2f209a7e950e5e8a',
    messagingSenderId: '987615597119',
    projectId: 'personalnote-37151',
    storageBucket: 'personalnote-37151.firebasestorage.app',
    iosBundleId: 'com.example.securityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj7y8wHNIt1TG8q6UkD5WHXBlXvgUAb_g',
    appId: '1:987615597119:web:69bec49ae9c40a4b0e5e8a',
    messagingSenderId: '987615597119',
    projectId: 'personalnote-37151',
    authDomain: 'personalnote-37151.firebaseapp.com',
    storageBucket: 'personalnote-37151.firebasestorage.app',
    measurementId: 'G-Y9EQ3RQ5NJ',
  );
}
